### ISSUE TITLE
Java public method in abstract class is not being generated to js/typescript

### ISSUE THREAD

**Issue by Displee** [cincheo/jsweet#220]
Examine the following piece of plain Java code:
```
package com.test;

import static jsweet.dom.Globals.console;

public class Test {

	public static abstract class AbstractTest {

		public void draw(int x, int y) {
			draw(x, y, 1, -1, 1);
		}

		public abstract void draw(int i_1, int i_2, int i_3, int i_4, int i_5);

	}

	public static class AbstractTestImpl extends AbstractTest {

		@Override
		public void draw(int i_1, int i_2, int i_3, int i_4, int i_5) {
			console.log("Hello world.");
		}

	}

	public static void main(String[] args) {
		AbstractTest test = new AbstractTestImpl();
		test.draw(0, 0);
	}

}

```

The abstract method in AbstractTest is being generated, but the public method is not

Below is the result of the generated code.

Typescript:
```
/* Generated from Java with JSweet 1.2.0 - http://www.jsweet.org */
namespace com.test {
    export class Test {
        public static main(args : string[]) {
            let test : Test.AbstractTest = new Test.AbstractTestImpl();
            test.draw(0, 0);
        }
    }
    Test["__class"] = "com.test.Test";


    export namespace Test {

        export abstract class AbstractTest {
            public draw(i_1 : number, i_2 : number, i_3 : number = 1, i_4 : number = -1, i_5 : number = 1);
        }
        AbstractTest["__class"] = "com.test.Test.AbstractTest";


        export class AbstractTestImpl extends Test.AbstractTest {
            public draw(i_1? : any, i_2? : any, i_3? : any, i_4? : any, i_5? : any) : any {
                if(((typeof i_1 === 'number') || i_1 === null) && ((typeof i_2 === 'number') || i_2 === null) && ((typeof i_3 === 'number') || i_3 === null) && ((typeof i_4 === 'number') || i_4 === null) && ((typeof i_5 === 'number') || i_5 === null)) {
                    let __args = Array.prototype.slice.call(arguments);
                    return <any>(() => {
                        console.log("Hello world.");
                    })();
                } else if(((typeof i_1 === 'number') || i_1 === null) && ((typeof i_2 === 'number') || i_2 === null) && i_3 === undefined && i_4 === undefined && i_5 === undefined) {
                    return <any>this.draw$int$int(i_1, i_2);
                } else throw new Error('invalid overload');
            }
        }
        AbstractTestImpl["__class"] = "com.test.Test.AbstractTestImpl";

    }

}
```

Javascript:
```
/* Generated from Java with JSweet 1.2.0 - http://www.jsweet.org */
var com;
(function (com) {
    var test;
    (function (test_1) {
        var Test = (function () {
            function Test() {
            }
            Test.main = function (args) {
                var test = new Test.AbstractTestImpl();
                test.draw(0, 0);
            };
            return Test;
        }());
        test_1.Test = Test;
        Test["__class"] = "com.test.Test";
        var Test;
        (function (Test) {
            var AbstractTest = (function () {
                function AbstractTest() {
                }
                return AbstractTest;
            }());
            Test.AbstractTest = AbstractTest;
            AbstractTest["__class"] = "com.test.Test.AbstractTest";
            var AbstractTestImpl = (function (_super) {
                __extends(AbstractTestImpl, _super);
                function AbstractTestImpl() {
                    _super.apply(this, arguments);
                }
                AbstractTestImpl.prototype.draw = function (i_1, i_2, i_3, i_4, i_5) {
                    if (((typeof i_1 === 'number') || i_1 === null) && ((typeof i_2 === 'number') || i_2 === null) && ((typeof i_3 === 'number') || i_3 === null) && ((typeof i_4 === 'number') || i_4 === null) && ((typeof i_5 === 'number') || i_5 === null)) {
                        var __args = Array.prototype.slice.call(arguments);
                        return (function () {
                            console.log("Hello world.");
                        })();
                    }
                    else if (((typeof i_1 === 'number') || i_1 === null) && ((typeof i_2 === 'number') || i_2 === null) && i_3 === undefined && i_4 === undefined && i_5 === undefined) {
                        return this.draw$int$int(i_1, i_2);
                    }
                    else
                        throw new Error('invalid overload');
                };
                return AbstractTestImpl;
            }(Test.AbstractTest));
            Test.AbstractTestImpl = AbstractTestImpl;
            AbstractTestImpl["__class"] = "com.test.Test.AbstractTestImpl";
        })(Test = test_1.Test || (test_1.Test = {}));
    })(test = com.test || (com.test = {}));
})(com || (com = {}));
```

If I try to run the javascript in my browser, I get `Uncaught TypeError: this.draw$int$int is not a function`.

**Comment by renaudpawlak** [comment]
Thanks for reporting. Looks like a tricky one but I think I see the reason. I'll try to fix ASAP.

**Comment by renaudpawlak** [comment]
fixed in version 2.0.0-SNAPSHOT

**Comment by Displee** [comment]
I want to reopen this issue, because this is still not fixed. I just tried this in the online sandbox, and it doesn't work there either.

This is my pom.xml:
```
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <groupId>org.jsweet</groupId>
    <artifactId>jsweet-quickstart</artifactId>
    <version>2.0.0-SNAPSHOT</version>
    <name>JSweet quick start</name>
    <description>A simple project structure to get started with JSweet</description>
    <developers>
        <developer>
            <id>rpawlak</id>
            <name>Renaud Pawlak</name>
            <email>renaud.pawlak@gmail.com</email>
        </developer>
    </developers>
    <licenses>
        <license>
            <name>The Apache Software License, Version 2.0</name>
            <url>http://www.apache.org/licenses/LICENSE-2.0.txt</url>
            <distribution>repo</distribution>
        </license>
    </licenses>
    <pluginRepositories>
        <pluginRepository>
            <id>jsweet-plugins-release</id>
            <name>plugins-release</name>
            <url>http://repository.jsweet.org/artifactory/plugins-release-local</url>
        </pluginRepository>
        <pluginRepository>
            <snapshots />
            <id>jsweet-plugins-snapshots</id>
            <name>plugins-snapshot</name>
            <url>http://repository.jsweet.org/artifactory/plugins-snapshot-local</url>
        </pluginRepository>
    </pluginRepositories>
    <repositories>
        <repository>
            <id>jsweet-central</id>
            <name>libs-release</name>
            <url>http://repository.jsweet.org/artifactory/libs-release-local</url>
        </repository>
        <reposito
```ry>
            <snapshots />
            <id>jsweet-snapshots</id>
            <name>libs-snapshot</name>
            <url>http://repository.jsweet.org/artifactory/libs-snapshot-local</url>
        </repository>
    </repositories>
    <build>
        <plugins>
            <plugin>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.1</version>
                <configuration>
                    <source>1.8</source>
                    <target>1.8</target>
                    <fork>true</fork>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.jsweet</groupId>
                <artifactId>jsweet-maven-plugin</artifactId>
                <version>1.2.0</version>
                <configuration>
                    <verbose>true</verbose>
                    <tsOut>target/ts</tsOut>
                    <outDir>target/js</outDir>
                    <candiesJsOut>webapp</candiesJsOut>
                    <targetVersion>ES5</targetVersion>
                    <bundle>true</bundle>
                    <bundlesDirectory>target/js/bundle</bundlesDirectory>
                </configuration>
                <executions>
                    <execution>
                        <id>generate-js</id>
                        <phase>generate-sources</phase>
                        <goals>
                            <goal>jsweet</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
        <pluginManagement>
            <plugins>

            </plugins>
        </pluginManagement>
    </build>
    <dependencies>
        <dependency>
            <groupId>org.jsweet</groupId>
            <artifactId>jsweet-core</artifactId>
            <version>5-SNAPSHOT</version>
        </dependency>
        <dependency>
            <groupId>org.jsweet.candies</groupId>
            <artifactId>j4ts</artifactId>
            <version>0.3.0-SNAPSHOT</version>
        </dependency>
        <dependency>
            <groupId>org.jsweet.candies.ext</groupId>
            <artifactId>angular</artifactId>
            <version>1.4.0-SNAPSHOT</version>
        </dependency>
        <dependency>
            <groupId>org.jsweet.candies.ext</groupId>
            <artifactId>angular-route</artifactId>
            <version>1.2.0-SNAPSHOT</version>
        </dependency>
        <dependency>
            <groupId>org.jsweet.candies.ext</groupId>
            <artifactId>node</artifactId>
            <version>7.5.0</version>
        </dependency>
        <dependency>
            <groupId>org.jsweet.candies.ext</groupId>
            <artifactId>express</artifactId>
            <version>4.14.0</version>
        </dependency>
        <dependency>
            <groupId>org.jsweet.candies.ext</groupId>
            <artifactId>express-errorhandler</artifactId>
            <version>4.14.0</version>
        </dependency>
        <dependency>
            <groupId>org.jsweet.candies.ext</groupId>
            <artifactId>express-body-parser</artifactId>
            <version>4.14.0</version>
        </dependency>
        <dependency>
            <groupId>org.jsweet.candies.ext</groupId>
            <artifactId>angular-material</artifactId>
            <version>1.1.3</version>
        </dependency>
        <dependency>
            <groupId>org.jsweet.candies.ext</groupId>
            <artifactId>socket.io</artifactId>
            <version>1.4.5</version>
        </dependency>
    </dependencies>
</project>

**Comment by renaudpawlak** [comment]
To use version 2 (soon to be released), you need to replace:
```xml
            <plugin>
                <groupId>org.jsweet</groupId>
                <artifactId>jsweet-maven-plugin</artifactId>
                <version>1.2.0</version>
```

with:

```xml
            <plugin>
                <groupId>org.jsweet</groupId>
                <artifactId>jsweet-maven-plugin</artifactId>
                <version>2.0.0-SNAPSHOT</version>
```

Additionally, you should also update your J4TS version... replace  ``<version>0.3.0-SNAPSHOT</version>`` with ``<version>0.5.0-SNAPSHOT</version>``.

**Comment by Displee** [comment]
I get this error when updating my J4TS:

`[ERROR] Failed to execute goal on project jsweet-quickstart: Could not resolve dependencies for project org.jsweet:jsweet-quickstart:jar:2.0.0-SNAPSHOT: Failed to collect dependencies at org.jsweet.candies:j4ts:jar:0.5.0-SNAPSHOT: Failed to read artifact descriptor for org.jsweet.candies:j4ts:jar:0.5.0-SNAPSHOT: Could not transfer artifact org.jsweet.candies:j4ts:pom:0.5.0-SNAPSHOT from/to jsweet-central (http://repository.jsweet.org/artifactory/libs-release-local): Failed to transfer file: http://repository.jsweet.org/artifactory/libs-release-local/org/jsweet/candies/j4ts/0.5.0-SNAPSHOT/j4ts-0.5.0-SNAPSHOT.pom. Return code is: 409 , ReasonPhrase:Conflict. -> [Help 1]`

**Comment by renaudpawlak** [comment]
I have (re)deployed J4TS 0.5.0-SNAPSHOT. Could you try again? (make sure to clean your Maven cache/local repo from JSweet first just in case).

**Comment by Displee** [comment]
Still doesn't work, I removed the org/jsweet folder in my .m2/repository multiple times, but nothing worked. I also cloned the jsweet quickstart project on another place, which didn't work either. Still getting the same error.

**Comment by Displee** [comment]
I'm using maven 3, does that affect something?

**Comment by renaudpawlak** [comment]
Nope. It is probably a problem with J4TS dependencies. I am currently working towards the release so it can explain this problem. You can try to remove completely J4TS from your dependencies and see what happens (you might not be using too much Java APIs and JSweet may be able to compile without J4TS)... Or you can simple wait a little bit until I fix it (should be a matter of days).

**Comment by Displee** [comment]
Can't wait for it, any ETA yet?

**Comment by renaudpawlak** [comment]
Thanks for reminding me. Too many things to do for the release :(
Have you tried removing J4TS from your dependencies? What happens then? The official way for using JSweet v2 will be *without* J4TS, so you'd better get used to it ;)

**Comment by Displee** [comment]
After re-importing some jsweet classes, it worked. Thanks alot!

**Comment by renaudpawlak** [comment]
Great! Did it work with or without J4TS in the end? It's important for me to know if the new way is starting to work well for other users...

**Comment by Displee** [comment]
Without J4TS. I removed it before, but then all my imports broke. So I thought that it was not a good sign. Never thought of re-importing my classes again, until now.
