### ISSUE TITLE
Error 500 with repository.jsweet.org (Internal Server Error). Something wrong with the server?

### ISSUE THREAD

**Issue by mathieu-bergeron** [cincheo/jsweet#718]
Hi, 

As of today (Feb 25 2022), I'm getting some Error 500 in my Gradle build (from repository.jsweet.org). Is there something wrong with the server?

I've tested with the jsweet-quickstart and the maven build also fails with similar errors:

`[ERROR] Failed to execute goal org.jsweet:jsweet-maven-plugin:3.1.0:jsweet (generate-js) on project jsweet-quickstart: Execution generate-js of goal org.jsweet:jsweet-maven-plugin:3.1.0:jsweet failed: Plugin org.jsweet:jsweet-maven-plugin:3.1.0 or one of its dependencies could not be resolved: Failed to collect dependencies at org.jsweet:jsweet-maven-plugin:jar:3.1.0 -> org.jsweet:jsweet-transpiler:jar:3.1.0 -> org.jsweet.ext:typescript.java-ts.core:jar:2.0.3: Failed to read artifact descriptor for org.jsweet.ext:typescript.java-ts.core:jar:2.0.3: Could not transfer artifact org.jsweet.ext:typescript.java-ts.core:pom:2.0.3 from/to jsweet-plugins-release (https://repository.jsweet.org/artifactory/plugins-release-local): Received fatal alert: internal_error -> [Help 1]
`
Warmly,
Mathieu

PS: In Gradle, I have the following errors:
```

> Could not resolve org.jsweet.ext:typescript.java-ts.core:2.0.3.
  Required by:
      unspecified:unspecified:unspecified > org.jsweet:jsweet-gradle-plugin:3.1.0 > org.jsweet:jsweet-transpiler:3.1.0
   > Could not resolve org.jsweet.ext:typescript.java-ts.core:2.0.3.
      > Could not get resource 'http://repository.jsweet.org/artifactory/libs-release-local/org/jsweet/ext/typescript.java-ts.core/2.0.3/typescript.java-ts.core-2.0.3.pom'.
         > Could not GET 'http://repository.jsweet.org/artifactory/libs-release-local/org/jsweet/ext/typescript.java-ts.core/2.0.3/typescript.java-ts.core-2.0.3.pom'. Received status code 500 from server: Internal Server Error
> Could not resolve org.jsweet.ext:sourcemap-builder:1.0.0.
  Required by:
      unspecified:unspecified:unspecified > org.jsweet:jsweet-gradle-plugin:3.1.0 > org.jsweet:jsweet-transpiler:3.1.0
   > Could not resolve org.jsweet.ext:sourcemap-builder:1.0.0.
      > Could not get resource 'http://repository.jsweet.org/artifactory/libs-release-local/org/jsweet/ext/sourcemap-builder/1.0.0/sourcemap-builder-1.0.0.pom'.
         > Could not GET 'http://repository.jsweet.org/artifactory/libs-release-local/org/jsweet/ext/sourcemap-builder/1.0.0/sourcemap-builder-1.0.0.pom'. Received status code 500 from server: Internal Server Error

```

**Comment by lgrignon** [comment]
Hello @mathieu-bergeron

We are currently working on this. Migrating DNS to a new service. Sorry for this temporary inconvenience.

**Comment by mathieu-bergeron** [comment]
No worries. Thanks :)
Mathieu

**Comment by lgrignon** [comment]
We fixed it this morning. Is it working for you? Please close this issue if this is the case

**Comment by mathieu-bergeron** [comment]
It works! Thanks a bunch and thank you for JSweet, it's an awesome project :)

Bonne journée!
Mathieu

**Comment by mathieu-bergeron** [comment]
Oh crap, the error is back! Sorry to be the bearer of bad news ;-)
Mathieu

PS: I've tested jsweet-quickstart from home and from a server (in a different network) and I have the same Error 500 I had Friday:

`[ERROR] Failed to execute goal org.jsweet:jsweet-maven-plugin:3.1.0:jsweet (generate-js) on project jsweet-quickstart: Execution generate-js of goal org.jsweet:jsweet-maven-plugin:3.1.0:jsweet failed: Plugin org.jsweet:jsweet-maven-plugin:3.1.0 or one of its dependencies could not be resolved: Failed to collect dependencies at org.jsweet:jsweet-maven-plugin:jar:3.1.0 -> org.jsweet:jsweet-transpiler:jar:3.1.0 -> org.jsweet.ext:typescript.java-ts.core:jar:2.0.3: Failed to read artifact descriptor for org.jsweet.ext:typescript.java-ts.core:jar:2.0.3: Could not transfer artifact org.jsweet.ext:typescript.java-ts.core:pom:2.0.3 from/to jsweet-plugins-release (https://repository.jsweet.org/artifactory/plugins-release-local): Certificate for <repository.jsweet.org> doesn't match any of the subject alternative names: [jsweet.org, ssl.jsweet.org, www.jsweet.org] -> [Help 1]`

**Comment by mathieu-bergeron** [comment]
No worries. Just wanted to let you know. Yeah, SSL issues are a pain :(

**Comment by radman-x** [comment]
I am having the same type of error:

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  01:28 min
[INFO] Finished at: 2022-02-28T11:23:42-06:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.jsweet:jsweet-maven-plugin:3.1.0:jsweet (generate-js) on project jsweet-quickstart: Execution generate-js of goal org.jsweet:jsweet-maven-plugin:3.1.0:jsweet failed: Plugin org.jsweet:jsweet-maven-plugin:3.1.0 or one of its dependencies could not be resolved: Failed to collect dependencies at org.jsweet:jsweet-maven-plugin:jar:3.1.0 -> org.jsweet:jsweet-transpiler:jar:3.1.0 -> org.jsweet.ext:typescript.java-ts.core:jar:2.0.3: Failed to read artifact descriptor for org.jsweet.ext:typescript.java-ts.core:jar:2.0.3: Could not transfer artifact org.jsweet.ext:typescript.java-ts.core:pom:2.0.3 from/to jsweet-plugins-release (https://repository.jsweet.org/artifactory/plugins-release-local): transfer failed for https://repository.jsweet.org/artifactory/plugins-release-local/org/jsweet/ext/typescript.java-ts.core/2.0.3/typescript.java-ts.core-2.0.3.pom: Certificate for <repository.jsweet.org> doesn't match any of the subject alternative names: [jsweet.org, ssl.jsweet.org, www.jsweet.org] -> [Help 1]
[

**Comment by renaudpawlak** [comment]
Service is temporary down for SSL migration. Sorry for the inconvenience but unfortunately it is complicated to migrate apparently.

**Comment by lgrignon** [comment]
Hello @mathieu-bergeron @radman-x 
Is it better for you? You can try to clear DNS cache. It should be fixed by now.

Please close if it's ok

**Comment by radman-x** [comment]
Gets closer but still fails -- maybe a different bug? Not sure how to "clear DNS cache" -- please explain.

Also, JSweet sandbox is still down with "Service Unavailable" message (when browsing Chrome to "http://www.jsweet.org/jsweet-live-sandbox/").

Here is the long error message:

[WARNING]
[WARNING] Some problems were encountered while building the effective model for org.jsweet:jsweet-quickstart:jar:3.1.0
[WARNING] 'version' contains an expression but should be a constant. @ org.jsweet:jsweet-quickstart:${jsweet.transpiler.version}, H:\RadTIME\TestCode\AugmentedReality\jsweet\jsweet-quickstart\pom.xml, line 6, column 11
[WARNING]
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING]
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING]
[INFO]
[INFO] --------------------< org.jsweet:jsweet-quickstart >--------------------
[INFO] Building JSweet quick start 3.1.0
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] --- jsweet-maven-plugin:3.1.0:jsweet (generate-js) @ jsweet-quickstart ---
[WARNING] Error injecting: org.jsweet.JSweetMojo
java.lang.TypeNotPresentException: Type org.jsweet.JSweetMojo not present
    at org.eclipse.sisu.space.URLClassSpace.loadClass (URLClassSpace.java:147)
    at org.eclipse.sisu.space.NamedClass.load (NamedClass.java:46)
    at org.eclipse.sisu.space.AbstractDeferredClass.get (AbstractDeferredClass.java:48)
    at com.google.inject.internal.ProviderInternalFactory.provision (ProviderInternalFactory.java:85)
    at com.google.inject.internal.InternalFactoryToInitializableAdapter.provision (InternalFactoryToInitializableAdapter.java:57)
    at com.google.inject.internal.ProviderInternalFactory$1.call (ProviderInternalFactory.java:66)
    at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision (ProvisionListenerStackCallback.java:112)
    at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision (ProvisionListenerStackCallback.java:127)
    at com.google.inject.internal.ProvisionListenerStackCallback.provision (ProvisionListenerStackCallback.java:66)
    at com.google.inject.internal.ProviderInternalFactory.circularGet (ProviderInternalFactory.java:61)
    at com.google.inject.internal.InternalFactoryToInitializableAdapter.get (InternalFactoryToInitializableAdapter.java:47)
    at com.google.inject.internal.InjectorImpl$1.get (InjectorImpl.java:1050)
    at org.eclipse.sisu.inject.Guice4$1.get (Guice4.java:162)
    at org.eclipse.sisu.inject.LazyBeanEntry.getValue (LazyBeanEntry.java:81)
    at org.eclipse.sisu.plexus.LazyPlexusBean.getValue (LazyPlexusBean.java:51)
    at org.codehaus.plexus.DefaultPlexusContainer.lookup (DefaultPlexusContainer.java:263)
    at org.codehaus.plexus.DefaultPlexusContainer.lookup (DefaultPlexusContainer.java:255)
    at org.apache.maven.plugin.internal.DefaultMavenPluginManager.getConfiguredMojo (DefaultMavenPluginManager.java:520)    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:124)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:210)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:972)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:293)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:196)
    at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:498)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
Caused by: java.lang.UnsupportedClassVersionError: org/jsweet/JSweetMojo has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
    at java.lang.ClassLoader.defineClass1 (Native Method)
    at java.lang.ClassLoader.defineClass (ClassLoader.java:763)
    at java.security.SecureClassLoader.defineClass (SecureClassLoader.java:142)
    at java.net.URLClassLoader.defineClass (URLClassLoader.java:468)
    at java.net.URLClassLoader.access$100 (URLClassLoader.java:74)
    at java.net.URLClassLoader$1.run (URLClassLoader.java:369)
    at java.net.URLClassLoader$1.run (URLClassLoader.java:363)
    at java.security.AccessController.doPrivileged (Native Method)
    at java.net.URLClassLoader.findClass (URLClassLoader.java:362)
    at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClassFromSelf (ClassRealm.java:425)
    at org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy.loadClass (SelfFirstStrategy.java:42)
    at org.codehaus.plexus.classworlds.realm.ClassRealm.unsynchronizedLoadClass (ClassRealm.java:271)
    at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass (ClassRealm.java:247)
    at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass (ClassRealm.java:239)
    at org.eclipse.sisu.space.URLClassSpace.loadClass (URLClassSpace.java:139)
    at org.eclipse.sisu.space.NamedClass.load (NamedClass.java:46)
    at org.eclipse.sisu.space.AbstractDeferredClass.get (AbstractDeferredClass.java:48)
    at com.google.inject.internal.ProviderInternalFactory.provision (ProviderInternalFactory.java:85)
    at com.google.inject.internal.InternalFactoryToInitializableAdapter.provision (InternalFactoryToInitializableAdapter.java:57)
    at com.google.inject.internal.ProviderInternalFactory$1.call (ProviderInternalFactory.java:66)
    at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision (ProvisionListenerStackCallback.java:112)
    at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision (ProvisionListenerStackCallback.java:127)
    at com.google.inject.internal.ProvisionListenerStackCallback.provision (ProvisionListenerStackCallback.java:66)
    at com.google.inject.internal.ProviderInternalFactory.circularGet (ProviderInternalFactory.java:61)
    at com.google.inject.internal.InternalFactoryToInitializableAdapter.get (InternalFactoryToInitializableAdapter.java:47)
    at com.google.inject.internal.InjectorImpl$1.get (InjectorImpl.java:1050)
    at org.eclipse.sisu.inject.Guice4$1.get (Guice4.java:162)
    at org.eclipse.sisu.inject.LazyBeanEntry.getValue (LazyBeanEntry.java:81)
    at org.eclipse.sisu.plexus.LazyPlexusBean.getValue (LazyPlexusBean.java:51)
    at org.codehaus.plexus.DefaultPlexusContainer.lookup (DefaultPlexusContainer.java:263)
    at org.codehaus.plexus.DefaultPlexusContainer.lookup (DefaultPlexusContainer.java:255)
    at org.apache.maven.plugin.internal.DefaultMavenPluginManager.getConfiguredMojo (DefaultMavenPluginManager.java:520)    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:124)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:210)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:972)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:293)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:196)
    at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:498)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  0.932 s
[INFO] Finished at: 2022-02-28T15:45:15-06:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.jsweet:jsweet-maven-plugin:3.1.0:jsweet (generate-js) on project jsweet-quickstart: Execution generate-js of goal org.jsweet:jsweet-maven-plugin:3.1.0:jsweet failed: Unable to load the mojo 'jsweet' in the plugin 'org.jsweet:jsweet-maven-plugin:3.1.0' due to an API incompatibility: org.codehaus.plexus.component.repository.exception.ComponentLookupException: org/jsweet/JSweetMojo has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
[ERROR] -----------------------------------------------------
[ERROR] realm =    plugin>org.jsweet:jsweet-maven-plugin:3.1.0
[ERROR] strategy = org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy
[ERROR] urls[0] = file:/C:/Users/Bruce%20A.%20Rady/.m2/repository/org/jsweet/jsweet-maven-plugin/3.1.0/jsweet-maven-plugin-3.1.0.jar
[ERROR] urls[1] = file:/C:/Users/Bruce%20A.%20Rady/.m2/repository/javax/enterprise/cdi-api/1.0/cdi-api-1.0.jar
[ERROR] urls[2] = file:/C:/Users/Bruce%20A.%20Rady/.m2/repository/javax/annotation/jsr250-api/1.0/jsr250-api-1.0.jar
[ERROR] urls[3] = file:/C:/Users/Bruce%20A.%20Rady/.m2/repository/org/codehaus/plexus/plexus-utils/3.2.1/plexus-utils-3.2.1.jar
[ERROR] urls[4] = file:/C:/Users/Bruce%20A.%20Rady/.m2/repository/org/sonatype/plexus/plexus-sec-dispatcher/1.4/plexus-sec-dispatcher-1.4.jar
[ERROR] urls[5] = file:/C:/Users/Bruce%20A.%20Rady/.m2/repository/org/sonatype/plexus/plexus-cipher/1.4/plexus-cipher-1.4.jar
[ERROR] urls[6] = file:/C:/Users/Bruce%20A.%20Rady/.m2/repository/org/apache/maven/maven-builder-support/3.6.3/maven-builder-support-3.6.3.jar
[ERROR] urls[7] = file:/C:/Users/Bruce%20A.%20Rady/.m2/repository/org/apache/maven/resolver/maven-resolver-util/1.4.1/maven-resolver-util-1.4.1.jar
[ERROR] urls[8] = file:/C:/Users/Bruce%20A.%20Rady/.m2/repository/org/apache/maven/shared/maven-shared-utils/3.2.1/maven-shared-utils-3.2.1.jar
[ERROR] urls[9] = file:/C:/Users/Bruce%20A.%20Rady/.m2/repository/org/eclipse/sisu/org.eclipse.sisu.inject/0.3.4/org.eclipse.sisu.inject-0.3.4.jar
[ERROR] urls[10] = file:/C:/Users/Bruce%20A.%20Rady/.m2/repository/com/google/inject/guice/4.2.1/guice-4.2.1-no_aop.jar
[ERROR] urls[11] = file:/C:/Users/Bruce%20A.%20Rady/.m2/repository/aopalliance/aopalliance/1.0/aopalliance-1.0.jar
[ERROR] urls[12] = file:/C:/Users/Bruce%20A.%20Rady/.m2/repository/com/google/guava/guava/25.1-android/guava-25.1-android.jar
[ERROR] urls[13] = file:/C:/Users/Bruce%20A.%20Rady/.m2/repository/com/google/code/findbugs/jsr305/3.0.2/jsr305-3.0.2.jar
[ERROR] urls[14] = file:/C:/Users/Bruce%20A.%20Rady/.m2/repository/org/checkerframework/checker-compat-qual/2.0.0/checker-compat-qual-2.0.0.jar
[ERROR] urls[15] = file:/C:/Users/Bruce%20A.%20Rady/.m2/repository/com/google/errorprone/error_prone_annotations/2.1.3/error_prone_annotations-2.1.3.jar
[ERROR] urls[16] = file:/C:/Users/Bruce%20A.%20Rady/.m2/repository/com/google/j2objc/j2objc-annotations/1.1/j2objc-annotations-1.1.jar
[ERROR] urls[17] = file:/C:/Users/Bruce%20A.%20Rady/.m2/repository/org/codehaus/mojo/animal-sniffer-annotations/1.14/animal-sniffer-annotations-1.14.jar
[ERROR] urls[18] = file:/C:/Users/Bruce%20A.%20Rady/.m2/repository/org/codehaus/plexus/plexus-component-annotations/2.1.0/plexus-component-annotations-2.1.0.jar
[ERROR] urls[19] = file:/C:/Users/Bruce%20A.%20Rady/.m2/repository/org/codehaus/plexus/plexus-interpolation/1.25/plexus-interpolation-1.25.jar
[ERROR] urls[20] = file:/C:/Users/Bruce%20A.%20Rady/.m2/repository/org/jsweet/jsweet-transpiler/3.1.0/jsweet-transpiler-3.1.0.jar
[ERROR] urls[21] = file:/C:/Users/Bruce%20A.%20Rady/.m2/repository/org/apache/commons/commons-text/1.3/commons-text-1.3.jar
[ERROR] urls[22] = file:/C:/Users/Bruce%20A.%20Rady/.m2/repository/commons-io/commons-io/2.4/commons-io-2.4.jar
[ERROR] urls[23] = file:/C:/Users/Bruce%20A.%20Rady/.m2/repository/log4j/log4j/1.2.17/log4j-1.2.17.jar
[ERROR] urls[24] = file:/C:/Users/Bruce%20A.%20Rady/.m2/repository/com/google/code/gson/gson/2.8.6/gson-2.8.6.jar
[ERROR] urls[25] = file:/C:/Users/Bruce%20A.%20Rady/.m2/repository/com/martiansoftware/jsap/2.1/jsap-2.1.jar
[ERROR] urls[26] = file:/C:/Users/Bruce%20A.%20Rady/.m2/repository/org/jsweet/ext/typescript.java-ts.core/2.0.3/typescript.java-ts.core-2.0.3.jar
[ERROR] urls[27] = file:/C:/Users/Bruce%20A.%20Rady/.m2/repository/com/eclipsesource/minimal-json/minimal-json/0.9.4/minimal-json-0.9.4.jar
[ERROR] urls[28] = file:/C:/Users/Bruce%20A.%20Rady/.m2/repository/org/tukaani/xz/1.8/xz-1.8.jar
[ERROR] urls[29] = file:/C:/Users/Bruce%20A.%20Rady/.m2/repository/org/jsweet/ext/sourcemap-builder/1.0.0/sourcemap-builder-1.0.0.jar
[ERROR] urls[30] = file:/C:/Users/Bruce%20A.%20Rady/.m2/repository/org/osgi/org.osgi.core/4.3.0/org.osgi.core-4.3.0.jar
[ERROR] urls[31] = file:/C:/Users/Bruce%20A.%20Rady/.m2/repository/org/apache/commons/commons-lang3/3.9/commons-lang3-3.9.jar
[ERROR] Number of foreign imports: 1
[ERROR] import: Entry[import  from realm ClassRealm[maven.api, parent: null]]
[ERROR]
[ERROR] -----------------------------------------------------
[ERROR]
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginContainerException

**Comment by radman-x** [comment]
BTW, thanx for the quick response!

**Comment by lgrignon** [comment]
Excuse me but this part of the error indicates that it has nothing to do with our recent operations: 

```
 [ERROR] Failed to execute goal org.jsweet:jsweet-maven-plugin:3.1.0:jsweet (generate-js) on project jsweet-quickstart: Execution generate-js of goal org.jsweet:jsweet-maven-plugin:3.1.0:jsweet failed: Unable to load the mojo 'jsweet' in the plugin 'org.jsweet:jsweet-maven-plugin:3.1.0' due to an API incompatibility: org.codehaus.plexus.component.repository.exception.ComponentLookupException: org/jsweet/JSweetMojo has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
```

Are you using the proper Java version for your JSweet version? This issue is dedicated to recent backend problems. Please open a new issue for your problem if you still get it after fixing your version (reminder : JSweet 2.x => Java 8, JSweet 3.x => Java >= 11)

Thanks

**Comment by lgrignon** [comment]
I am closing it. Please reopen if you still face issue with JSweet's servers
